### ISSUE TITLE
Set up OwnCloud

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/NCHRD#1]
On a server at Affinity Bridge

**Comment by PeaceGeeksProjects** [comment]
Kris is waiting for Mac to provide access to a server where he can install

**Comment by improvethings** [comment]
Use owncloud instead

**Comment by improvethings** [comment]
We are moving to ownCloud, as the requirements to use SecureDrop were too high, and it doesn't solve the needs as efficiently as owncloud does, and in less time. 

SecureDrop hardware requirements as an example, require 3 computers: https://docs.securedrop.org/en/latest/hardware.html

**Comment by PeaceGeeks** [comment]
Also, OwnCloud will live on the Backbone server.

**Comment by improvethings** [comment]
Owncloud is now up and running securely. Let me know if you have any questions.
