### ISSUE TITLE
Set up Jabber

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/NCHRD#20]

**Comment by improvethings** [comment]
Need to point chat.peacegeeks.org to the server at Backbone. Mack has let me know he made the change this morning.

**Comment by improvethings** [comment]
Need to have SSL certificate/key to secure the transport layer.

**Comment by improvethings** [comment]
Hit a bug, submitted it here:

https://github.com/processone/ejabberd/issues/910

**Comment by improvethings** [comment]
ejabberd is now setup. Would like Renee to verify it's working as intended.

**Comment by PeaceGeeks** [comment]
i have a concern with jitsi. when i sign out and sign back in again, it doesn't prompt me for a pw. this seems like a vulnerability?

**Comment by PeaceGeeksProjects** [comment]
This is probably because you 'remembered' PWD on a prior login.
Tools=>Options=>Security=>Saved Passwords...
and delete the saved passwords

**Comment by PeaceGeeks** [comment]
Yes that is correct. I have done so. @improvethings - do you consider this to be closed now?

**Comment by improvethings** [comment]
Yes, I consider this closed and working.
