### ISSUE TITLE
Setup Rocket.Chat

### ISSUE THREAD

**Issue by improvethings** [PeaceGeeksSociety/NCHRD#21]
I have installed Rocket.Chat and nginx as a reverse SSL proxy. 
Outstanding: 

1) Understanding how to block port 3000 from outside access, this does not seem to be in the documentation. 

2) Setup the access control lists (ACLs) to be invite only/new accounts need approval, instead of the default which is open to the public.

**Comment by improvethings** [comment]
Port 3000 is now blocked from the outside world. No one else seems to have done this, I think we might be the first. I notified the Rocket.Chat folks, so I bet they will update their documentation to secure future users.

**Comment by PeaceGeeks** [comment]
Rocket Chat is now working for text, but it is missing the email notification.
