### ISSUE TITLE
Review Martus Alternatives

### ISSUE THREAD

**Issue by improvethings** [PeaceGeeksSociety/NCHRD#24]
Try K-9 Mail with APG. 

Forms or spreadsheets on Android? Can it be filled out in Offline mode?

**Comment by improvethings** [comment]
There are no simple alternatives. The best solution is a spreadsheet form on a desktop computer encrypted with GnuPG. Android/smart phone devices are a big risk, as there is no reason to trust the hardware, operating system, or applications installed on it. Also, they have a GPS, mic, and video which is easy to access once compromised, and there are usually no tools to detect a compromise on these devices. 
When I tried with forms and templates, it was hard to use, and going to require several steps by the worker to be properly encrypted. 

Earlier in the project I also asked around, and no one else I know doing human rights work is using smart phone devices either at this stage.

**Comment by PeaceGeeks** [comment]
When you say 'When I tried with forms and templates' what are you referring to?

**Comment by improvethings** [comment]
I tried to create a form on my android device using HTML, and I tried K9 email drafts as a template, both were not simple or easy.
The K9 template was encrypted at least, but was just a plain text file that would be emailed to us, and we'd have to enter into a spreadsheet/database.

**Comment by improvethings** [comment]
I consider this ticket closed. 

Martus seems to be the best, assuming that Android and offline are requirements. 
We seem to be the only people I know trusting Android (I'm speaking next week at the Reboot Privacy & Security Conference on a panel with the director of security for Blackberry, where I will be telling the audience they should not be trusting their smartphone) in the human rights space. I would prefer we didn't. That said, based on the requirements, Martus seems to be the best choice. 

If there is an opportunity to review the requirements, I would recommend that.

**Comment by PeaceGeeksProjects** [comment]
Tx Kris,  Closing.
