### ISSUE TITLE
Questions to Martus

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/NCHRD#25]
In Martus, 

1. Can you enter the user info once and then hide the header?
2. Because of the header and keypad, there is almost no room on the screen to do the actual work
3. Can you provide a check box to indicate which sections have been completed?

**Comment by PeaceGeeks** [comment]
See Anna's most recent email as of Jan 15

**Comment by improvethings** [comment]
Emailed Anna. 

Kris to create a new app using the secure app generator.

**Comment by improvethings** [comment]
Access token not working in the secure app generator - staging environment, emailed Anna. Expect she will respond tomorrow as today is a holiday there.

**Comment by improvethings** [comment]
Benetech staging environment is still down. I have asked Anna to manually create the form, and it sounds like she'll have it for us shortly for the app for testing.

**Comment by improvethings** [comment]
The APK seems to be the best we're going to get it. I have provided Renee a copy, and have tested it myself.
